clone:
  depth: 1
  recursive: true

build:
  image: debian:latest
  privileged: true
  net: bridge
  #volumes:
    #- /var/run/docker.sock:/var/run/docker.sock
    #- /usr/bin/docker:/usr/bin/docker
    #- /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  commands:
    - apt-get update && apt-get install -y -q curl
    - curl -L https://get.docker.com/builds/Linux/x86_64/docker-1.7.1 > /usr/local/bin/docker
    - chmod +x /usr/local/bin/docker
    - docker -d &
    - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker version
    - docker-compose version
    - docker ps
    - docker-compose up $$DISTRO

matrix:
  DISTRO:
    - debian
#    - ubuntu
#    - centos7
