clone:
  depth: 1
  recursive: true

build:
  image: debian:latest
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  commands:
    - docker-compose up $$DISTRO

matrix:
  DISTRO:
    - debian
#    - ubuntu
#    - centos7
