clone:
  depth: 50
  recursive: true

build:
  image: quay.io/dennybaa/droneruby
  privileged: true
  environment:
    - DEBUG=1
    - ST2_GITURL=https://github.com/dennybaa/st2
    - ST2_GITREV=fixate-reqs-update
    - ST2_WAITFORSTART=20
    - ST2_TESTMODE=
    - ST2_BUILDLIST=
    - MISTRAL_ENABLED=
    - MISTRAL_GITURL=https://github.com/StackStorm/mistral
    - MISTRAL_GITREV=st2-0.13.2
    - MISTRAL_VERSION=2015.2
    - MISTRAL_RELEASE=1
    - POSTGRES_USER=mistral
    - POSTGRES_PASSWORD=StackStorm
    - BUILDHOST=bwheezy
    - TESTHOSTS=iwheezy
  commands:
    - echo 123
    #- ping -c 4 rabbitmq || exit 0
    #- docker-compose version || exit 0
    #- ./.drone/build.sh

compose:
  bwheezy:
    image: quay.io/stackstorm/packagingenv:wheezy
  iwheezy:
    image: quay.io/dennybaa/droneunit:wheezy
  rabbitmq:
    image: rabbitmq:management
  mongodb:
    image: mongo
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=mistral
      - POSTGRES_PASSWORD=StackStorm
